version: "3.9"

services:
  web:
    image: nginx:alpine
    container_name: astro-spa
    ports:
      - "8080:80"        # visit http://localhost:8080
    restart: unless-stopped
    pull_policy: always
    volumes:
      # Serve the built Astro output
      - ./app/astro/dist:/usr/share/nginx/html:ro

      # nginx configs
      - ./nginx/99-no-cache.conf:/etc/nginx/conf.d/99-no-cache.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/healthz"]
      interval: 15s
      timeout: 3s
      retries: 5
